# Generated by Django 4.2.9 on 2026-10-02 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='节点顺序')),
                ('sign_mode', models.CharField(choices=[('single', '单人签署'), ('any', '任一签署（或签）'), ('all', '多人会签')], default='single', max_length=20, verbose_name='签署方式')),
                ('use_active_admins', models.BooleanField(default=True, help_text='未指定审批人或指定人全部回避时，取在职管理员', verbose_name='在职管理员兜底')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审批节点',
                'verbose_name_plural': '审批节点',
                'db_table': 'wh_approval_node',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalNodeApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='node_approver_links', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='warehouse.approvalnode', verbose_name='所属节点')),
            ],
            options={
                'verbose_name': '节点审批人',
                'verbose_name_plural': '节点审批人',
                'db_table': 'wh_approval_node_approver',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='路线名称')),
                ('risk_level', models.CharField(blank=True, choices=[('normal', '普通物资'), ('elevated', '较高风险'), ('high', '高风险物资')], default='', help_text='为空表示不限风险等级', max_length=20, verbose_name='风险等级')),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='数量下限（含）')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='数量上限（含）')),
                ('receiver_dept', models.CharField(blank=True, default='', help_text='为空表示不限部门', max_length=100, verbose_name='领用部门')),
                ('purpose', models.CharField(blank=True, default='', help_text='为空表示不限用途', max_length=50, verbose_name='用途')),
                ('priority', models.PositiveIntegerField(default=100, help_text='数值越小越优先', verbose_name='优先级')),
                ('is_fallback', models.BooleanField(default=False, verbose_name='兜底路线')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审批路线',
                'verbose_name_plural': '审批路线',
                'db_table': 'wh_approval_route',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRouteEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('initial', '创建选定'), ('resubmit', '拒绝后重提'), ('reevaluate', '条件变化重评')], default='initial', max_length=20, verbose_name='评估类型')),
                ('conditions', models.JSONField(default=dict, verbose_name='申请条件快照')),
                ('matched_reasons', models.JSONField(default=list, verbose_name='命中原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='warehouse.approvalroute', verbose_name='命中路线')),
            ],
            options={
                'verbose_name': '审批路线评估记录',
                'verbose_name_plural': '审批路线评估记录',
                'db_table': 'wh_approval_route_evaluation',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True, verbose_name='版本号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效中'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='版本说明')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rule_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_rule_versions', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '审批规则版本',
                'verbose_name_plural': '审批规则版本',
                'db_table': 'wh_approval_rule_version',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField(default=1, verbose_name='路线代次')),
                ('node_order', models.PositiveIntegerField(verbose_name='节点顺序')),
                ('node_name', models.CharField(max_length=100, verbose_name='节点名称（快照）')),
                ('sign_mode', models.CharField(default='single', max_length=20, verbose_name='签署方式（快照）')),
                ('status', models.CharField(choices=[('waiting', '待激活'), ('pending', '待签署'), ('approved', '已同意'), ('rejected', '已拒绝'), ('recused', '已回避'), ('cancelled', '已取消')], default='waiting', max_length=20, verbose_name='任务状态')),
                ('remark', models.TextField(blank=True, verbose_name='审批意见')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='签署时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('replacement_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='warehouse.approvaltask', verbose_name='替补的任务')),
            ],
            options={
                'verbose_name': '审批签署任务',
                'verbose_name_plural': '审批签署任务',
                'db_table': 'wh_approval_task',
                'ordering': ['node_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='risk_level',
            field=models.CharField(choices=[('normal', '普通物资'), ('elevated', '较高风险'), ('high', '高风险物资')], default='normal', max_length=20, verbose_name='风险等级'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='current_node_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='当前节点顺序'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='purpose',
            field=models.CharField(blank=True, choices=[('case_handling', '办案使用'), ('daily_duty', '日常执勤'), ('training', '训练演练'), ('storage', '入库保管'), ('scrap', '报废处置'), ('other', '其他')], default='', max_length=50, verbose_name='用途'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='resubmitted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='warehouse.stockout', verbose_name='重提自申请'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='route_generation',
            field=models.PositiveIntegerField(default=1, help_text='条件变化重评且换路线时递增；签署任务按代次归属', verbose_name='路线代次'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='route_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='审批路线快照'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_out_operations', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('blocked', '无法流转'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='stock_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tasks', to='warehouse.stockout', verbose_name='出库申请'),
        ),
        migrations.AddField(
            model_name='approvalrouteevaluation',
            name='rule_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='warehouse.approvalruleversion', verbose_name='规则版本'),
        ),
        migrations.AddField(
            model_name='approvalrouteevaluation',
            name='stock_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='warehouse.stockout', verbose_name='出库申请'),
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='warehouse.approvalruleversion', verbose_name='所属版本'),
        ),
        migrations.AddField(
            model_name='approvalnode',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='warehouse.approvalroute', verbose_name='所属路线'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='rule_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='warehouse.approvalruleversion', verbose_name='规则版本'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['stock_out', 'status'], name='wh_approval_stock_o_3d2370_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['approver', 'status'], name='wh_approval_approve_86880d_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalroute',
            constraint=models.UniqueConstraint(condition=models.Q(('is_fallback', True)), fields=('version',), name='uniq_fallback_route_per_version'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalnodeapprover',
            unique_together={('node', 'approver')},
        ),
        migrations.AlterUniqueTogether(
            name='approvalnode',
            unique_together={('route', 'order')},
        ),
    ]
