# Generated by Django 4.2.9 on 2026-10-03 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('submit', '提交申请'), ('approve', '通过'), ('reject', '拒绝'), ('recuse', '主动回避'), ('auto_recuse', '自动回避'), ('delegate', '改派'), ('step_activate', '节点激活'), ('step_skip', '节点跳过'), ('step_block', '节点阻塞'), ('resubmit', '拒绝后重提'), ('reevaluate', '条件变化重新评估'), ('complete', '审批完成'), ('cancel', '撤销申请')], max_length=20, verbose_name='事件类型')),
                ('detail', models.TextField(blank=True, verbose_name='事件说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审批事件',
                'verbose_name_plural': '审批事件',
                'db_table': 'wh_approval_event',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(max_length=20, verbose_name='审批角色编码')),
                ('scope_dept', models.CharField(blank=True, default='', max_length=100, verbose_name='适用领用部门')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在岗')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='设置人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '审批角色指派',
                'verbose_name_plural': '审批角色指派',
                'db_table': 'wh_approval_role_assignment',
                'ordering': ['role_code', 'scope_dept', 'id'],
                'unique_together': {('role_code', 'scope_dept', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True, verbose_name='版本号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效中'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('nodes', models.JSONField(default=list, verbose_name='审批节点定义')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='版本说明')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_rule_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '审批规则版本',
                'verbose_name_plural': '审批规则版本',
                'db_table': 'wh_approval_rule_version',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(verbose_name='节点顺序')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('role_code', models.CharField(max_length=20, verbose_name='审批角色')),
                ('sign_policy', models.CharField(default='all', max_length=20, verbose_name='签署策略')),
                ('quorum', models.PositiveIntegerField(blank=True, null=True, verbose_name='通过人数门槛')),
                ('reason', models.TextField(blank=True, verbose_name='触发原因')),
                ('status', models.CharField(choices=[('pending', '待激活'), ('active', '签署中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('skipped', '已跳过'), ('blocked', '已阻塞')], default='pending', max_length=20, verbose_name='节点状态')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='激活时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '审批节点',
                'verbose_name_plural': '审批节点',
                'db_table': 'wh_approval_step',
                'ordering': ['stock_out', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='StepSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待签署'), ('approved', '已通过'), ('rejected', '已拒绝'), ('recused', '已回避'), ('skipped', '无需签署')], default='pending', max_length=20, verbose_name='签署状态')),
                ('source', models.CharField(default='normal', max_length=20, verbose_name='指派来源')),
                ('comment', models.TextField(blank=True, verbose_name='签署意见')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='签署时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='warehouse.approvalstep', verbose_name='审批节点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_signatures', to=settings.AUTH_USER_MODEL, verbose_name='签署人')),
            ],
            options={
                'verbose_name': '节点签署人',
                'verbose_name_plural': '节点签署人',
                'db_table': 'wh_step_signer',
                'ordering': ['id'],
                'unique_together': {('step', 'user')},
            },
        ),
        migrations.AlterModelOptions(
            name='stockout',
            options={'ordering': ['-created_at'], 'verbose_name': '出库申请', 'verbose_name_plural': '出库申请'},
        ),
        migrations.AddField(
            model_name='goods',
            name='risk_level',
            field=models.CharField(choices=[('normal', '普通耗材'), ('controlled', '受控物资'), ('high_risk', '高风险物资')], default='normal', max_length=20, verbose_name='风险等级'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='用途说明'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='purpose_type',
            field=models.CharField(choices=[('use', '执勤使用'), ('transfer', '调拨'), ('destruction', '销毁'), ('inspection', '检验鉴定'), ('other', '其他')], default='use', max_length=20, verbose_name='用途类型'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='reevaluated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reevaluations', to='warehouse.stockout', verbose_name='重新评估自'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='revised_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='warehouse.stockout', verbose_name='修订自'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='revision_no',
            field=models.PositiveIntegerField(default=1, verbose_name='修订号'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, verbose_name='风险等级快照'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='route_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='审批路线快照'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='warehouse.goods', verbose_name='货物'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_out_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '审批中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已撤销'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='stock_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='warehouse.stockout', verbose_name='出库申请'),
        ),
        migrations.AddField(
            model_name='approvalevent',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='warehouse.approvalstep', verbose_name='审批节点'),
        ),
        migrations.AddField(
            model_name='approvalevent',
            name='stock_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='warehouse.stockout', verbose_name='出库申请'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='current_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_stock_outs', to='warehouse.approvalstep', verbose_name='当前审批节点'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='rule_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='warehouse.approvalruleversion', verbose_name='规则版本'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('stock_out', 'order_index')},
        ),
    ]
