# Generated by Django 4.2.9 on 2026-10-02 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_approvalnode_approvalnodeapprover_approvalroute_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvaltask',
            options={'ordering': ['generation', 'node_order', 'id'], 'verbose_name': '审批签署任务', 'verbose_name_plural': '审批签署任务'},
        ),
    ]
